CREATE TABLE Sheet1(Column_1 VARCHAR(10),Column_2 VARCHAR(10),Column_3 VARCHAR(10),Column_4 VARCHAR(10),Column_5 VARCHAR(10));
INSERT INTO Sheet1 (Column_1,Column_2,Column_3,Column_4,Column_5) VALUES 
('create table acoustic-realm-395017.estudo_caso.cyclistic_2022 as (','','','',''),
('SELECT * FROM `acoustic-realm-395017.estudo_caso.cyclistic_202201` ','','','',''),
('union all ','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202202','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202203','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202204','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202205','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202206','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202207','','','',''),
('union all ','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202208','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202209','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202210','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202211','','','',''),
('union all','','','',''),
('select * from acoustic-realm-395017.estudo_caso.cyclistic_202212','','','',''),
(')','','','',''),
('#Verificar se h� duplicatas','','','',''),
('SELECT','','','',''),
('  ride_id','','','',''),
('  COUNT(ride_id) registros','','','',''),
('FROM','','','',''),
('  `acoustic-realm-395017.estudo_caso.cyclistic_2022`','','','',''),
('group by 1','','','',''),
('having count(ride_id) > 1','','','',''),
('#Verificar padr�o no id','','','',''),
('SELECT','','','',''),
('  DISTINCT LENGTH(ride_id)','','','',''),
('FROM','','','',''),
('  `acoustic-realm-395017.estudo_caso.cyclistic_2022`','','','',''),
('LIMIT','','','',''),
('  1000','','','',''),
('#Verificar se a quantidade de esta��es batem','','','',''),
('select ','','','',''),
('count(distinct concat(start_lat',',','start_lng)) inicial_station',' ',''),
('count(distinct concat(end_lat',',','end_lng)) end_station ','',''),
('from acoustic-realm-395017.estudo_caso.cyclistic_final_table','','','',''),
('#Adi��o de vari�veis e filtros','','','',''),
('create or replace table acoustic-realm-395017.estudo_caso.intermediary_table as (','','','',''),
('with c1 as (','','','',''),
('            SELECT','','','',''),
('              *',' ','','',''),
('              st_geogpoint(start_lng',' start_lat) AS inic_coor','','',''),
('              st_geogpoint(end_lng',' end_lat) AS end_coor','','',''),
('              datetime_diff(ended_at',' started_at',' minute) AS trip_duration_min','',''),
('              FORMAT_DATE('%k'',' started_at) AS trip_start','','',''),
('              FORMAT_DATE('%A'',' started_at) AS trip_dayofweek','','',''),
('              FORMAT_DATE('%b'',' started_at) AS trip_month','','',''),
('              FORMAT_DATE('%Q'',' started_at) AS trip_quarter','','',''),
('            FROM','','','',''),
('              `acoustic-realm-395017.estudo_caso.cyclistic_2022`','','','',''),
('            )','','','',''),
('select  ','','','',''),
('  * except(inic_coor','end_coor)',' ','',''),
('  ifnull(round(st_distance(inic_coor',' end_coor)/1000','1)','0) AS distance_km',''),
('  concat(round(start_lat','2)',',','round(start_lng','2)) station_coord'),
('from c1','','','',''),
('where trip_duration_min >= 0','','','',''),
('and end_lat is not null','','','',''),
('and started_at <> ended_at','','','',''),
(')','','','',''),
('#M�ximos e m�nimos dura��o viagem','','','',''),
('SELECT','','','',''),
('  MAX(trip_duration_min) max_duracao','','','',''),
('  MIN(trip_duration_min) min_duracao','','','',''),
('FROM','','','',''),
('  `acoustic-realm-395017.estudo_caso.tabela_final`','','','',''),
('LIMIT','','','',''),
('  1000','','','',''),
('#Remo��o outliers medida z score','','','',''),
('create or replace table acoustic-realm-395017.estudo_caso.cyclistic_final_table as (','','','',''),
('WITH TripStats AS (','','','',''),
('  SELECT','','','',''),
('    AVG(trip_duration_min) AS avg_duration','','','',''),
('    STDDEV(trip_duration_min) AS stddev_duration','','','',''),
('  FROM','','','',''),
('    acoustic-realm-395017.estudo_caso.intermediary_table','','','',''),
(')','','','',''),
('select * from acoustic-realm-395017.estudo_caso.intermediary_table','','','',''),
('where ','','','',''),
('  abs((trip_duration_min - (select avg_duration from TripStats))/(select stddev_duration from TripStats)) <= 3 ','','','',''),
(')','','','',''),
(' ','','','','');